chore(fe): migrate code formatter to biome (#1014)
Co-authored-by: Hu Yueh-Wei <wei.hu.tw@gmail.com>

diff --git a/ai_agents/demo/Dockerfile b/ai_agents/demo/Dockerfile
--- a/ai_agents/demo/Dockerfile
+++ b/ai_agents/demo/Dockerfile
@@ -1,4 +1,4 @@
-FROM node:22-alpine AS base
+FROM oven/bun:alpine AS base
 
 # 1. Install dependencies only when needed
 FROM base AS deps
@@ -8,13 +8,15 @@ RUN apk add --no-cache libc6-compat
 WORKDIR /app
 
 # Install dependencies based on the preferred package manager
-COPY package.json .yarnrc* yarn.lock* package-lock.json* pnpm-lock.yaml* ./
+COPY package.json bun.lock ./
 RUN \
-    if [ -f yarn.lock ]; then corepack enable yarn && yarn --immutable; \
-    elif [ -f package-lock.json ]; then npm ci; \
-    elif [ -f pnpm-lock.yaml ]; then npm install -g pnpm@10.2.0 && pnpm i; \
-    else echo "Lockfile not found." && exit 1; \
-    fi
+  if [ -f yarn.lock ]; then corepack enable yarn && yarn --immutable; \
+  elif [ -f package-lock.json ]; then npm ci; \
+  elif [ -f pnpm-lock.yaml ]; then npm install -g pnpm@10.2.0 && pnpm i; \
+  elif [ -f bun.lockb ]; then bun i --frozen-lockfile; \
+  elif [ -f bun.lock ]; then bun i --frozen-lockfile; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
 
 # 2. Rebuild the source code only when needed
 FROM base AS builder
@@ -28,11 +30,13 @@ COPY . .
 ENV NEXT_TELEMETRY_DISABLED=1
 
 RUN \
-    if [ -f yarn.lock ]; then corepack enable yarn && yarn run build; \
-    elif [ -f package-lock.json ]; then npm run build; \
-    elif [ -f pnpm-lock.yaml ]; then npm install -g pnpm@10.2.0 && pnpm run build; \
-    else echo "Lockfile not found." && exit 1; \
-    fi
+  if [ -f yarn.lock ]; then corepack enable yarn && yarn run build; \
+  elif [ -f package-lock.json ]; then npm run build; \
+  elif [ -f pnpm-lock.yaml ]; then npm install -g pnpm@10.2.0 && pnpm run build; \
+  elif [ -f bun.lockb ]; then bun run build; \
+  elif [ -f bun.lock ]; then bun run build; \
+  else echo "Lockfile not found." && exit 1; \
+  fi
 
 # 3. Production image, copy all the files and run next
 FROM base AS runner
